#!/bin/sh

cd "${0%/*}"

if test -f target/indicators-service.jar; then
    java -jar projects/indicators-service/target/indicators-service.jar
else
    echo "Service jar not found: 'target/indicators-service.jar'. Please run ../../build-indicators-service"
fi

# To test once running, try:
#
# curl -i http://localhost:8890/indicators
