#!/bin/sh

cd "${0%/*}"
if test -f target/indicators-service.jar; then
  docker build -t indicators-service .
else
  echo "Service jar not found: 'target/indicators-service.jar'. Please run ../../build-indicators-service"
fi